language: ruby

sudo: false

cache: bundler

services:
  - redis-server

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
  - jruby-19mode

script:
  - bundle exec rspec

matrix:
  allow_failures:
    - rvm: 2.1.0
